#!/bin/bash

VAR=${PWD}

export CLASSPATH=$VAR/server/:$VAR/middleware/

#Setting values for server name and server port
if [ $# -eq 2 ];then
	SERVERNAME=$1
	PORT=$2
else
	echo "Usage: ./clientscript <middleware-hostname> <middleware-port>"
	exit -1
fi

echo "Server is $SERVERNAME"
echo "Port is $PORT"
echo "Starting client..."
cd ./client/
echo "grant codeBase \"file:$VAR/client\" { permission java.security.AllPermission; };" > client.policy
javac *.java
java -Djava.security.policy=client.policy -classpath .:../server:../middleware Client $SERVERNAME $PORT
